### ISSUE TITLE
Any support for the Dasung Paperlike Color 25.3"?

### ISSUE THREAD

**Issue by ultrafragile** [leoluk/paperlike-go#13] opened 2024-04-12 21:45 UTC
https://shop.dasung.com/products/dasung-paperlike-color-world-first-color-e-ink-monitor

**Comment by leoluk** [comment] 2024-04-13 10:27
Shouldn't be too hard - someone who has it needs to reverse engineer it

**Comment by jtbg** [comment] 2024-04-15 13:20
@ultrafragile if you have the Color 253, would you be willing to set up a sandbox environment to poke around? 

(or if you'd prefer, I could ship you a rpi4 that is pre-configured for the remote access)

**Comment by leoluk** [comment] 2024-04-15 13:29
There's also Windows software here that could potentially be reverse engineered: https://www.dasung.com/h-col-112.html

When I briefly investigated the Paperlike 253 a while ago, it looked like they switched from I2C to a USB serial device and the protocol was different: https://github.com/leoluk/paperlike-go/issues/9. Chances are it's the same for the newer one.

(in related news, this new color screen looks amazing and I just pre-ordered one - I blame this GitHub issue)

**Comment by mezzarobba** [comment] 2024-05-19 13:16
> When I briefly investigated the Paperlike 253 a while ago, it looked like they switched from I2C to a USB serial device and the protocol was different: #9. Chances are it's the same for the newer one.

I can confirm that: the `DS253.c` file released by Dasung works with the color version. In addition to the settings listed in the program, a few other commands appear to be accepted (0x0b with parameters from 1 to 4, 0x11) but I was not able to figure out what they do.

**Comment by leoluk** [comment] 2024-07-03 11:54
I tested it and can confirm that it's the same protocol - closing this as a duplicate of #9

**Closed as not planned by leoluk** 2024-07-03 11:54 UTC
Labels: enhancement
